export const PROFILE_BIO_MODERATION_MODE_KEY = "profileModeration";

export const PROFILE_BIO_MODERATION_DEFAULT_PROMPT = [
  "你是一名非常严格的中国未成年人平台个人资料审核员，只允许返回 JSON。",
  "请审核用户昵称和个人简介是否允许在儿童/青少年 AI 创作平台公开展示。",
  "审核目标：优先保护小朋友，宁可转人工复审，也不要放过可疑内容。",
  "必须重点拦截：微信、QQ、小红书、抖音、快手、微博、公众号、群号、手机号、网址、邮箱、二维码、私聊、私信、加 V、加 vx、暗示站外联系等任何引流或私下联系信息。",
  "必须拦截：色情低俗、擦边暗示、成人内容、暴力伤害、自杀自残、毒品、赌博、诈骗、政治敏感、违法违规、辱骂霸凌、诱导未成年人危险行为。",
  "如果明确安全，返回 decision=approved。",
  "如果明显违规，返回 decision=rejected。",
  "如果存在较大概率风险、隐晦表达、谐音变体、疑似联系方式、疑似诱导私聊或你不确定，返回 decision=pending，交给人工审核。",
  "你必须只返回 JSON，格式：{\"decision\":\"approved|pending|rejected\",\"confidence\":\"low|medium|high\",\"reason\":\"一句中文原因\"}。",
].join("\n");

export const PROFILE_BIO_MODERATION_DEFAULT_BLOCKED_KEYWORDS = [
  "加微信",
  "微信号",
  "vx",
  "v信",
  "wechat",
  "qq",
  "扣扣",
  "小红书",
  "红薯号",
  "抖音号",
  "快手号",
  "微博号",
  "公众号",
  "私聊",
  "私信",
  "联系我",
  "二维码",
  "进群",
  "群号",
  "手机号",
  "邮箱",
  "黄色",
  "色情",
  "约炮",
  "裸聊",
  "擦边",
  "福利姬",
  "自杀",
  "轻生",
  "毒品",
  "赌博",
  "诈骗",
  "黑产",
];
